baseURL = "https://jkaye2012.github.io"
languageCode = "en-us"
title = "Organizing Chaos"
theme = "strange-case"

[author]
name = "Jordan Kaye"

[params]
description = "Thoughts on software and technical leadership"
colorScheme = "scheme-darkbrown"

[[menu.icons]]
name = "GitHub"
url = "https://github.com/jkaye2012"
post = "<img src=\"/images/github.png\"></img>"

[[menu.icons]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/jordan-kaye-8bb64537/"
post = "<img width=\"32px\" height=\"32px\" src=\"/images/linkedin.png\"></img>"

[[menu.main]]
name = "About me"
url = "/about"
