baseURL = "https://jkaye2012.github.io"
languageCode = "en-us"
title = "Organizing Chaos"
theme = "mini"
enableEmoji = true

[params]
author = "Jordan Kaye"
bio = "Thoughts on technical leadership and software engineering"
description = "Thoughts on technical leadership and software engineering"
colorScheme = "scheme-darkbrown"
subscribe = "rss"
copyright = "Copyright 2023 | Jordan Kaye"
showPowerBy = false
customCSS = ["/css/custom.css"]

[[params.links]]
name = "Lexicon"
path = "/lexicon/"

[[params.links]]
name = "Follow"
path = "/follow/"

[markup]
  [markup.highlight]
    anchorLineNos = true
    lineNos = true
    lineNumbersInTable = false
    style = 'gruvbox-light'

[social]
github = "https://github.com/jkaye2012"
linkedin = "https://www.linkedin.com/in/jordan-kaye-8bb64537/"
