baseURL = "https://jkaye2012.github.io"
languageCode = "en-us"
title = "Organizing Chaos"
theme = "mini"

[params]
author = "Jordan Kaye"
description = "Thoughts on software and technical leadership"
colorScheme = "scheme-darkbrown"
enableRSS = true
copyright = "Copyright 2023 | Jordan Kaye"
showPowerBy = false
customCSS = ["css/custom.css"]

[social]
github = "https://github.com/jkaye2012"
linkedin = "https://www.linkedin.com/in/jordan-kaye-8bb64537/"

