---
title: Introduction
date: 2020-12-12
draft: false
---

* Background

  My name is Jordan Kaye. I'm currently the Head of Technology for [[http://www.belvederetrading.com][Belvedere Trading]]'s office in Boulder, focused on research and development
  of fully automated market-making systems.

  As a leader, I believe that maintaining trust through honesty and consistent expectations is key to building high-performing teams and organizations.

  As a technologist, I enjoy exploring different programming languages and paradigms to design robust and easily maintainable systems. I believe
  that embracing many different languages (and their corresponding communities) is a great way to expand one's knowledge
  and understanding of software.

  When I'm not working or writing code, I love lifting weights, skiing, hiking, and gaming.

* Contact

  I'm always happy to hear from other technology enthusiasts. The best way to reach me is though [[mailto:jkaye@belvederetrading.com][my work address]].

  If you're a recruiter, I'm not currently looking for work, but you can feel free to connect with me on LinkedIn via the link on the sidebar.
